DATA_PATH = "training_datas/playing_cards"
ANNOTATIONS_ORG_FILE = "_annotations.coco.json"
ANNOTATIONS_CSV_FILE = "annos.csv"
TRAINED_MODEL_PATH = "trained_models"
MODEL_FILE = "best.pt"
LOG_PATH = "tensorboard"
TESTS_IMAGE_PATH = "testing_images"
TEST_OUTPUT_PATH = "outputs/images"
